<?php

return [
    'modules' => [
        'startups',
        'website_health',
        'users',
        'categories',
        'blog',
        'advertising',
        'messages',
        'reports',
        'moderation',
        'payments',
        'admin_notifications',
        'subscribers',
        'scheduled_tasks',
        'settings',
        'gateways',
    ],
    'route_patterns' => [
        'admin.startups.*' => 'startups',
        'admin.hero-request.*' => 'startups',
        'admin.startup-websites.*' => 'website_health',
        'admin.users.*' => 'users',
        'admin.categories.*' => 'categories',
        'admin.blog.*' => 'blog',
        'admin.ad-spots.*' => 'advertising',
        'admin.contact-messages.*' => 'messages',
        'admin.startup-reports.*' => 'reports',
        'admin.reports.*' => 'reports',
        'admin.subscribers.*' => 'subscribers',
        'admin.scheduled-tasks.*' => 'scheduled_tasks',
        'admin.seo' => 'settings',
        'admin.about' => 'settings',
        'admin.settings.*' => 'settings',
        'admin.gateways.*' => 'gateways',
        'admin.operations.moderation*' => 'moderation',
        'admin.operations.payments*' => 'payments',
        'admin.operations.notifications*' => 'admin_notifications',
    ],
];
