<?php

namespace App\Console\Commands;

use App\Models\ScheduledTask;
use App\Services\SitemapService;
use Illuminate\Console\Command;

class SitemapGenerateCommand extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'sitemap:generate';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Generate sitemap.xml and record the run in scheduled_tasks.';

    /**
     * Execute the console command.
     */
    public function handle(): int
    {
        try {
            /** @var SitemapService $service */
            $service = app(SitemapService::class);
            $path = $service->generate();

            /** @var ScheduledTask|null $task */
            $task = ScheduledTask::where('name', 'sitemap')->first();
            if ($task) {
                $task->markSuccess('Sitemap generated by sitemap:generate command. Path: ' . $path);
            }

            $this->info('Sitemap generated successfully at: ' . $path);

            return self::SUCCESS;
        } catch (\Throwable $e) {
            /** @var ScheduledTask|null $task */
            $task = ScheduledTask::where('name', 'sitemap')->first();
            if ($task) {
                $task->markFailed($e->getMessage());
            }

            $this->error('Failed to generate sitemap: ' . $e->getMessage());

            return self::FAILURE;
        }
    }
}

